source 'https://rubygems.org'

# TODO: Can't this be included via ../../headhunter.gemspec?
gem 'headhunter', path: '../../'

gem 'rails'
gem 'rspec-rails'
gem 'capybara'
gem 'jazz_hands' # Use Pry and its extensions instead of IRB
