# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

ENV['HEADHUNTER'] ||= 'true' # Normally, headhunter is only loaded when submitting HEADHUNTER=true on the command line. For sake of simplicity, we activate it here generally.

require File.expand_path('../config/application', __FILE__)

Dummy::Application.load_tasks

require 'rspec/core'
require 'rspec/core/rake_task'

task default: :spec
